package ru.netology.kotlin.a5.Odb

data class Post (
    val content: String
)

val list = listOf(
    Post("1"),
    Post("2"),
    Post("3"),
    Post("5"),
    Post("4"),
    Post("5"),
    Post("6"),
    Post("7"),
    Post("8"),
    Post("9"),
    Post("10"),
    Post("11"),
    Post("12"),
    Post("13"),
    Post("15"),
    Post("14"),
    Post("15"),
    Post("16"),
    Post("17"),
    Post("18"),
    Post("19"),
    Post("20"),
    Post("111"),
    Post("112"),
    Post("113"),
    Post("115"),
    Post("114"),
    Post("115"),
    Post("116"),
    Post("117"),
    Post("118"),
    Post("119"),
    Post("120"),
    Post("  2"),
    Post("       5"),
    Post("1"),
    Post("  2"),
    Post("       5"),
    Post("1"),
    Post("  2"),
    Post("       5"),
    Post("1"),
    Post("  2"),
    Post("       5"),
    Post("1"),
    Post("  2"),
    Post("       5"),
    Post("1"),
    Post("  2"),
    Post("       5"),
    Post("1"),
    Post("  2"),
    Post("    3")
)